/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Weather;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Hello World");
        int a=10;
        int b=10;
        int c=a+b;
        System.out.print(c);
        new MainFrame().setVisible(true);
    }
}
