/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Weather;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;
/**
 *
 * @author khushal
 */
public class MainFrame extends javax.swing.JFrame {
static String name=" ";
static String temprature=" ";
static String q = "Jodhpur";
static String appid = "bebd9da120762f2b44fb9b1f056c90ef";
static String units = "metric";
static String desc="";
static String fl="";
static String mintemp="";
static String maxtemp="";
static String pressure="";
static String humid="";
static String sl="";
String gl="";
int flag=0;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        mainpanel.setVisible(false);
   
        doYourWork();
        this.setAlwaysOnTop(true);
        this.setFocusableWindowState(true);
        setDefaultLookAndFeelDecorated(rootPaneCheckingEnabled);
          
             
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        txtdesc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        btnselect = new javax.swing.JButton();
        city_name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desc_temp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        desc_pre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        desc_fl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        desc_humid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        desc_min_temp = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        desc_sl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        desc_max_temp = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        desc_gl = new javax.swing.JLabel();
        txttemp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        mainpanel.setAutoscrolls(true);
        mainpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtdesc.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txtdesc.setText("Description");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)), "Select City", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poppins Medium", 0, 18))); // NOI18N

        searchbox.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
        });

        btnselect.setText("Select");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnselect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnselect))
                .addContainerGap())
        );

        city_name.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        city_name.setText("City Name");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Description", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Poppins Medium", 0, 14), new java.awt.Color(11, 20, 98))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setText("Temprature");
        jPanel1.add(jLabel1);

        desc_temp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_temp.setText("var");
        jPanel1.add(desc_temp);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Pressure");
        jPanel1.add(jLabel3);

        desc_pre.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_pre.setText("var");
        jPanel1.add(desc_pre);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Feels Like");
        jPanel1.add(jLabel5);

        desc_fl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_fl.setText("var");
        jPanel1.add(desc_fl);

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Humidity");
        jPanel1.add(jLabel7);

        desc_humid.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_humid.setText("var");
        jPanel1.add(desc_humid);

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("Min. Temprature");
        jPanel1.add(jLabel9);

        desc_min_temp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_min_temp.setText("var");
        jPanel1.add(desc_min_temp);

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel11.setText("Sea Level");
        jPanel1.add(jLabel11);

        desc_sl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_sl.setText("var");
        jPanel1.add(desc_sl);

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel13.setText("Max. Temprature");
        jPanel1.add(jLabel13);

        desc_max_temp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_max_temp.setText("var");
        jPanel1.add(desc_max_temp);

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel15.setText("Ground Level");
        jPanel1.add(jLabel15);

        desc_gl.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        desc_gl.setText("var");
        jPanel1.add(desc_gl);

        txttemp.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        txttemp.setText("Temprature");

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city_name)
                            .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(city_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtdesc)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(mainpanel);
        mainpanel.getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        q=searchbox.getText().toString();
        doYourWork();
    }//GEN-LAST:event_btnselectActionPerformed

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      q=searchbox.getText().toString();
        doYourWork();
   }
    }//GEN-LAST:event_searchboxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//doYourWork();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainFrame().setVisible(true);
              
               System.out.println(name);
                           System.out.println(temprature);
               
                
            }
        });
    }
private void doYourWork()
{
     Call<WeatherModel> call = new Retrofit.Builder()
        .baseUrl("https://api.openweathermap.org")
        .addConverterFactory(GsonConverterFactory.create())
        .build().create(ApiInterface.class).getCurrentCityWeatherInfo(q,appid,units);
     call.enqueue(new Callback<WeatherModel>(){
                    @Override
                    @SuppressWarnings("null")
                    public void onResponse(Call<WeatherModel> call, Response<WeatherModel> response) {
                       if(response.code()==200)
                       {
                           WeatherModel weatherRes = response.body();
                           name = weatherRes.name;
                           temprature=weatherRes.main.temp;
                           desc=weatherRes.weather.get(0).description;
                           fl=weatherRes.main.feels_like;
                           mintemp=weatherRes.main.temp_min;
                           maxtemp=weatherRes.main.temp_max;
                           pressure=weatherRes.main.pressure;
                           humid=weatherRes.main.humidity;
                           sl=weatherRes.main.sea_level;
                           gl=weatherRes.main.grnd_level;
                           System.out.println(name);
                           System.out.println(weatherRes.main.temp);
                           desc_gl.setText(weatherRes.main.grnd_level);
                       }
                       if(response.code()==404)
                           JOptionPane.showMessageDialog(getGlassPane(), "Item Not Found","Error" , HEIGHT);
                       mainpanel.setVisible(true);
                     
                        city_name.setText(name);
                        txttemp.setText(temprature);
                        txtdesc.setText(desc);
                        desc_temp.setText(temprature);
                        desc_fl.setText(fl);
                        desc_min_temp.setText(mintemp);
                        desc_max_temp.setText(maxtemp);
                        desc_pre.setText(pressure);
                        desc_humid.setText(humid);
                        desc_sl.setText(sl);
                       // desc_gl.setText(gl);
                    }

                    @Override
                    public void onFailure(Call<WeatherModel> call, Throwable t) {
                         JOptionPane.showMessageDialog(null, "Check your internet connection");
                        JOptionPane.showMessageDialog(null, t);
                    }
                    
                });
}
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnselect;
    javax.swing.JLabel city_name;
    private javax.swing.JLabel desc_fl;
    private javax.swing.JLabel desc_gl;
    private javax.swing.JLabel desc_humid;
    private javax.swing.JLabel desc_max_temp;
    private javax.swing.JLabel desc_min_temp;
    private javax.swing.JLabel desc_pre;
    private javax.swing.JLabel desc_sl;
    private javax.swing.JLabel desc_temp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JTextField searchbox;
    private javax.swing.JLabel txtdesc;
    private javax.swing.JLabel txttemp;
    // End of variables declaration//GEN-END:variables
}
